-- voeg de twee nieuwe kolommen toe aan de klant tabel
ALTER TABLE KLANT ADD IS_STUDENT WEL_OF_NIET null
ALTER TABLE KLANT ADD GEBOORTEDATUM	DATE null

-- populeer is_student kolom
UPDATE KLANT SET IS_STUDENT = 1
WHERE KLANTNUMMER % 8 = 0
UPDATE KLANT SET IS_STUDENT = 0
WHERE IS_STUDENT IS NULL

-- populeer geboortedatum kolom
UPDATE KLANT SET GEBOORTEDATUM = DATEADD(YEAR,(KLANTNUMMER*541349)%95,'1920-01-01')

-- update naar not null
ALTER TABLE [KLANT] ALTER COLUMN [IS_STUDENT] WEL_OF_NIET NOT NULL
ALTER TABLE [KLANT] ALTER COLUMN [GEBOORTEDATUM] DATE NOT NULL
