-- codegeneratie voor alle int columns in een database om er een constraint op te zetten.
DECLARE @table varchar(100)
DECLARE @column varchar(100)
DECLARE columncursor CURSOR FOR
SELECT TABLE_NAME, COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS
WHERE DATA_TYPE = 'int'
DECLARE @ddl VARCHAR(MAX) = ''  

OPEN columncursor
FETCH NEXT FROM columncursor INTO @table, @column
WHILE @@FETCH_STATUS = 0
BEGIN
	SET @ddl = @ddl + 'ALTER TABLE ' + @table + ' ADD CONSTRAINT '
	+ 'checkNegatief' + @table + '_' + @column + ' CHECK (' + @column + ' >= 0)'
	FETCH NEXT FROM columncursor INTO @table, @column
	PRINT @ddl
	SET @ddl = ''
END
CLOSE columncursor
DEALLOCATE columncursor


ALTER TABLE BESTELLING ADD CONSTRAINT checkNegatiefBESTELLING_ORDERID CHECK (ORDERID >= 0)
ALTER TABLE BESTELLING ADD CONSTRAINT checkNegatiefBESTELLING_WORKSHOPID CHECK (WORKSHOPID >= 0)
ALTER TABLE BESTELLING ADD CONSTRAINT checkNegatiefBESTELLING_ONDERDEELID CHECK (ONDERDEELID >= 0)
ALTER TABLE BESTELLING ADD CONSTRAINT checkNegatiefBESTELLING_LEVERANCIERID CHECK (LEVERANCIERID >= 0)
ALTER TABLE BESTELLING ADD CONSTRAINT checkNegatiefBESTELLING_AANTAL CHECK (AANTAL >= 0)
ALTER TABLE EVENT_VOOR_STATION ADD CONSTRAINT checkNegatiefEVENT_VOOR_STATION_STATIONID CHECK (STATIONID >= 0)
ALTER TABLE EVENT_VOOR_STATION ADD CONSTRAINT checkNegatiefEVENT_VOOR_STATION_EVENTID CHECK (EVENTID >= 0)
ALTER TABLE FIETS ADD CONSTRAINT checkNegatiefFIETS_FIETSID CHECK (FIETSID >= 0)
ALTER TABLE FIETSINSTATION ADD CONSTRAINT checkNegatiefFIETSINSTATION_FIETSID CHECK (FIETSID >= 0)
ALTER TABLE FIETSINSTATION ADD CONSTRAINT checkNegatiefFIETSINSTATION_STATIONID CHECK (STATIONID >= 0)
ALTER TABLE FIETSINSTATION ADD CONSTRAINT checkNegatiefFIETSINSTATION_FIETSPOST CHECK (FIETSPOST >= 0)
ALTER TABLE FIETSONDERDEEL ADD CONSTRAINT checkNegatiefFIETSONDERDEEL_ONDERDEELID CHECK (ONDERDEELID >= 0)
ALTER TABLE FIETSONDERDEEL ADD CONSTRAINT checkNegatiefFIETSONDERDEEL_MAXIMUM_AANTAL CHECK (MAXIMUM_AANTAL >= 0)
ALTER TABLE FIETSONDERDEEL ADD CONSTRAINT checkNegatiefFIETSONDERDEEL_MINIMAAL_AANTAL CHECK (MINIMAAL_AANTAL >= 0)
ALTER TABLE FIETSONDERDEELBIJLEVERANCIER ADD CONSTRAINT checkNegatiefFIETSONDERDEELBIJLEVERANCIER_LEVERANCIERID CHECK (LEVERANCIERID >= 0)
ALTER TABLE FIETSONDERDEELBIJLEVERANCIER ADD CONSTRAINT checkNegatiefFIETSONDERDEELBIJLEVERANCIER_ONDERDEELID CHECK (ONDERDEELID >= 0)
ALTER TABLE FIETSONDERDEELINWORKSHOP ADD CONSTRAINT checkNegatiefFIETSONDERDEELINWORKSHOP_ONDERDEELID CHECK (ONDERDEELID >= 0)
ALTER TABLE FIETSONDERDEELINWORKSHOP ADD CONSTRAINT checkNegatiefFIETSONDERDEELINWORKSHOP_WORKSHOPID CHECK (WORKSHOPID >= 0)
ALTER TABLE FIETSONDERDEELINWORKSHOP ADD CONSTRAINT checkNegatiefFIETSONDERDEELINWORKSHOP_AANTAL CHECK (AANTAL >= 0)
ALTER TABLE KLANT ADD CONSTRAINT checkNegatiefKLANT_KLANTNUMMER CHECK (KLANTNUMMER >= 0)
ALTER TABLE KLANTHEEFTABONNEMENT ADD CONSTRAINT checkNegatiefKLANTHEEFTABONNEMENT_KLANTNUMMER CHECK (KLANTNUMMER >= 0)
ALTER TABLE KLANTHEEFTABONNEMENT ADD CONSTRAINT checkNegatiefKLANTHEEFTABONNEMENT_CREDITKAARTNUMMER CHECK (CREDITKAARTNUMMER >= 0)
ALTER TABLE LENING ADD CONSTRAINT checkNegatiefLENING_FIETSID CHECK (FIETSID >= 0)
ALTER TABLE LENING ADD CONSTRAINT checkNegatiefLENING_KLANTNUMMER CHECK (KLANTNUMMER >= 0)
ALTER TABLE LENING ADD CONSTRAINT checkNegatiefLENING_START_STATION CHECK (START_STATION >= 0)
ALTER TABLE LENING ADD CONSTRAINT checkNegatiefLENING_EIND_STATION CHECK (EIND_STATION >= 0)
ALTER TABLE LEVERANCIER ADD CONSTRAINT checkNegatiefLEVERANCIER_LEVERANCIERID CHECK (LEVERANCIERID >= 0)
ALTER TABLE MONTEURDIENST ADD CONSTRAINT checkNegatiefMONTEURDIENST_WERKNEMERID CHECK (WERKNEMERID >= 0)
ALTER TABLE MONTEURDIENST ADD CONSTRAINT checkNegatiefMONTEURDIENST_WORKSHOPID CHECK (WORKSHOPID >= 0)
ALTER TABLE ONGROUNDREPARATIES ADD CONSTRAINT checkNegatiefONGROUNDREPARATIES_WERKNEMERID CHECK (WERKNEMERID >= 0)
ALTER TABLE ONGROUNDREPARATIES ADD CONSTRAINT checkNegatiefONGROUNDREPARATIES_FIETSID CHECK (FIETSID >= 0)
ALTER TABLE ONGROUNDTEAM ADD CONSTRAINT checkNegatiefONGROUNDTEAM_TEAMID CHECK (TEAMID >= 0)
ALTER TABLE OUTQUEUE ADD CONSTRAINT checkNegatiefOUTQUEUE_FIETSID CHECK (FIETSID >= 0)
ALTER TABLE OUTQUEUE ADD CONSTRAINT checkNegatiefOUTQUEUE_WORKSHOPID CHECK (WORKSHOPID >= 0)
ALTER TABLE REPARATIE ADD CONSTRAINT checkNegatiefREPARATIE_FIETSID CHECK (FIETSID >= 0)
ALTER TABLE REPARATIE ADD CONSTRAINT checkNegatiefREPARATIE_ONDERDEELID CHECK (ONDERDEELID >= 0)
ALTER TABLE REPARATIE ADD CONSTRAINT checkNegatiefREPARATIE_WERKNEMERID CHECK (WERKNEMERID >= 0)
ALTER TABLE REPARATIEQUEUE ADD CONSTRAINT checkNegatiefREPARATIEQUEUE_FIETSID CHECK (FIETSID >= 0)
ALTER TABLE REPARATIEQUEUE ADD CONSTRAINT checkNegatiefREPARATIEQUEUE_WORKSHOPID CHECK (WORKSHOPID >= 0)
ALTER TABLE REPARATIEQUEUE ADD CONSTRAINT checkNegatiefREPARATIEQUEUE_VOLGNUMMER CHECK (VOLGNUMMER >= 0)
ALTER TABLE ROUTINGCARD ADD CONSTRAINT checkNegatiefROUTINGCARD_TEAMID CHECK (TEAMID >= 0)
ALTER TABLE ROUTINGCARD ADD CONSTRAINT checkNegatiefROUTINGCARD_STATIONID CHECK (STATIONID >= 0)
ALTER TABLE SPECIAAL_EVENEMENT ADD CONSTRAINT checkNegatiefSPECIAAL_EVENEMENT_EVENTID CHECK (EVENTID >= 0)
ALTER TABLE STATION ADD CONSTRAINT checkNegatiefSTATION_STATIONID CHECK (STATIONID >= 0)
ALTER TABLE STATION ADD CONSTRAINT checkNegatiefSTATION_STATIONNUMMER CHECK (STATIONNUMMER >= 0)
ALTER TABLE STATION ADD CONSTRAINT checkNegatiefSTATION_ARRONDISSEMENT CHECK (ARRONDISSEMENT >= 0)
ALTER TABLE STATION ADD CONSTRAINT checkNegatiefSTATION_CAPACITEIT CHECK (CAPACITEIT >= 0)
ALTER TABLE WERKNEMER ADD CONSTRAINT checkNegatiefWERKNEMER_WERKNEMERID CHECK (WERKNEMERID >= 0)
ALTER TABLE ADMINTABEL ADD CONSTRAINT checkNegatiefADMINTABEL_WERKNEMERID CHECK (WERKNEMERID >= 0)
ALTER TABLE WERKNEMERINONGROUNDTEAM ADD CONSTRAINT checkNegatiefWERKNEMERINONGROUNDTEAM_TEAMID CHECK (TEAMID >= 0)
ALTER TABLE WERKNEMERINONGROUNDTEAM ADD CONSTRAINT checkNegatiefWERKNEMERINONGROUNDTEAM_WERKNEMERID CHECK (WERKNEMERID >= 0)
ALTER TABLE WORKSHOP ADD CONSTRAINT checkNegatiefWORKSHOP_WORKSHOPID CHECK (WORKSHOPID >= 0)
ALTER TABLE TAAK ADD CONSTRAINT checkNegatiefTAAK_TAAKID CHECK (TAAKID >= 0)
